oasisprotocol/cli

cmd/root.go, config/config.go, wallet/file/file.go
=> fix(wallet): Use the correct directory to store file-based accounts

cmd/network/governance/list.go
=> fix(cmd): Add missing --height to governance list

wallet/ledger/signer.go
=> ledger: Fix ed25519-adr8 switch

docs/network.md, examples/network-set-rpc/00-list.out, examples/network-set-rpc/02-list.out, examples/network-set-rpc/config/cli.toml, examples/network/00-list.out, examples/network/02-list.out, examples/network/04-list.out, examples/network/add-unix.in.static, examples/network/config/cli.toml
See https://github.com/oasisprotocol/docs/pull/588#discussion_r1396389809
=> docs: Replace serverdir/ -> node/ for consistency with other docs

examples/wallet/import-file-unmnemonic.in.static, examples/wallet/import-file-unmnemonic.out.static
Required by https://github.com/oasisprotocol/docs/pull/651
=> examples: Add import-file on unmenmonic pem file

LICENSE-docs, README.md
See https://github.com/oasisprotocol/docs/pull/440.
=> docs: License the documentation under CC-BY 4.0

cmd/rofl/mgmt.go
Add Oasis CLI support for https://github.com/oasisprotocol/oasis-sdk/pull/1958.
Required by https://github.com/oasisprotocol/oasis-web3-gateway/issues/603
=> feat(rofl/create): Add --scheme

build/cargo/cargo.go, cmd/rofl/build.go
=> feat(cmd/rofl): Add --mode argument to build command

cmd/rofl/mgmt.go, docs/README.md, docs/rofl.md, examples/rofl/build-sgx-unsafe.in.static, examples/rofl/build-sgx.in.static, examples/rofl/create-npa.in.static, examples/rofl/create.in.static, examples/rofl/create.out.static, examples/rofl/identity.in.static, examples/rofl/identity.out.static, examples/rofl/remove-npa.in.static, examples/rofl/remove.in.static, examples/rofl/remove.out.static, examples/rofl/show-np.in.static, examples/rofl/show.in.static, examples/rofl/show.out.static, examples/rofl/trust-root-np.in.static, examples/rofl/trust-root.in.static, examples/rofl/trust-root.out.static, examples/rofl/update-npa.in.static, examples/rofl/update-self.in.static, examples/rofl/update.in.static, examples/rofl/update.out.static
=> Add ROFL documentation

build/rofl/manifest.go, build/rofl/manifest_test.go, cmd/rofl/mgmt.go, docs/rofl.md, examples/rofl/create.in.static, examples/rofl/init.in.static, examples/rofl/init.out.static
=> feat(cmd/rofl): Only create deployments in create not init

.golangci.yml, build/rofl/manifest.go, cmd/rofl/mgmt.go, go.mod, go.sum
=> feat(cmd/rofl): Add repository/author/license and other app metadata

cmd/rofl/mgmt.go
Detect docker-compose.yml, docker-compose.yaml, compose.yml if they already exist on `oasis rofl init`. Useful, if you want to ROFLize existing containers.
Partial fix for https://github.com/oasisprotocol/cli/issues/384
=> rofl: Detect compose-like file on init, if it exists

build/measurement/tdx_qemu.go, cmd/rofl/build/build.go, cmd/rofl/build/sgx.go, cmd/rofl/build/tdx.go, cmd/rofl/common/identity.go, cmd/rofl/identity.go
=> feat(cmd/rofl): Populate component identity in the generated bundle

build/cargo/cargo.go
This fixes an issue when fetching metadata for Rust packages which are part of workspaces since in those cases `cargo metadata` returns information about all packages in the workspace instead of just the package in the current working directory.
=> fix(build): Fix Rust metadata discovery for packages in workspaces

cmd/account/allow.go, cmd/account/amend_commission_schedule.go, cmd/account/burn.go, cmd/account/delegate.go, cmd/account/deposit.go, cmd/account/entity.go, cmd/account/node_unfreeze.go, cmd/account/transfer.go, cmd/account/undelegate.go, cmd/account/withdraw.go, cmd/common/selector.go, cmd/common/transaction.go, cmd/contract.go, cmd/network/governance/create.go, cmd/network/governance/vote.go, cmd/paratime/register.go, cmd/paratime/show.go, cmd/paratime/statistics.go, cmd/rofl/common/manifest.go, cmd/rofl/mgmt.go, cmd/rofl/trust_root.go, cmd/tx.go
Sleeker UX for first-time users/ROFL developers.
Partial fix for https://github.com/oasisprotocol/cli/issues/384
Fixes https://github.com/oasisprotocol/cli/issues/10
=> Add hint for the Testnet faucet, no account, no ParaTime and failed deposit

cmd/rofl/mgmt.go
=> cmd/rofl/init: Init git repository if applicable

.golangci.yml, cmd/rofl/build/container.go, go.mod
=> cmd/rofl/build: Check if service images contain FQDNs

cmd/rofl/deploy.go, cmd/rofl/push.go, cmd/rofl/rofl.go
Fixes https://github.com/oasisprotocol/cli/issues/498
=> cmd/rofl: Add 'rofl push' command

build/rofl/provider/defaults.go, cmd/rofl/deploy.go
Use Oasis-managed Mainnet ROFL provider by default.
=> Add Mainnet provider address

build/rofl/artifacts.go, build/rofl/manifest.go, build/rofl/manifest_test.go, cmd/rofl/mgmt.go
=> Fix artifact upgrade and bump rofl-containers

cmd/common/selector.go, cmd/rofl/common/manifest.go, cmd/rofl/common/manifest_test.go, cmd/rofl/machine/machine.go, cmd/rofl/machine/mgmt.go, cmd/rofl/mgmt.go
=> feat(cmd/rofl): Add machine change-admin subcommand

cmd/rofl/common/policy.go, cmd/rofl/deploy.go, cmd/rofl/machine/mgmt.go, docs/rofl.md, examples/rofl/deploy.out.static, examples/rofl/machine-remove.in.static, examples/rofl/machine-remove.out.static, examples/rofl/machine-top-up.out.static
=> feat: add warning for user about refund policy
